### ISSUE TITLE
为什么要替换pubspec文件下flutter assets的配置，所有文件都显示出来，文件会很长

### ISSUE THREAD

**Issue by xiangzy1** [Fly-Mix/flr-vscode-extension#1]

**Comment by CodeEagle** [comment]
这个默认规则生成，根据配置，这个资源路径的长度不影响使用

**Comment by xzylzz** [comment]
flutter assets设置一个文件夹也行的吧，和flr配置保持一致会有问题吗？太长了就是看着不舒服😂

**Comment by CodeEagle** [comment]
后面看下怎么优化

**Comment by YK-Unit** [comment]
> flutter assets设置一个文件夹也行的吧，和flr配置保持一致会有问题吗？太长了就是看着不舒服😂

在基于配置进行开发的模式下，配置文件应该优先选择“详细配置”，其次才是“模糊配置”（一般发生在需要手动操作的无奈场景下）——所以这种详细导致的“视觉长”是有益的，它可方便你进行调试，如调试看某个资源是否正确声明了。

PS：关于你说的“长”，其实当你在通过git的方式添加库依赖，又或者在添加自定义字体资源时，你会发现官方也是这种“长”的风格。

**Comment by xzylzz** [comment]
> > flutter assets设置一个文件夹也行的吧，和flr配置保持一致会有问题吗？太长了就是看着不舒服😂
> 
> 在基于配置进行开发的模式下，配置文件应该优先选择“详细配置”，其次才是“模糊配置”（一般发生在需要手动操作的无奈场景下）——而且这种详细导致的“视觉长”是有益的，它可方便你进行调试，如调试看某个资源是否正确声明了。
> 
> PS：关于你说的“长”，其实当你在通过git的方式添加库依赖，又或者在添加自定义字体资源时，你会发现官方也是这种“长”的风格。

我是这么觉得，还是建议把选择模糊配置还是详细配置的选择交给用户，毕竟pubspec里面并不是只有assets的配置

**Comment by TshineZheng** [comment]
我现在想在assets加个音频文件，要怎么加？

**Comment by YK-Unit** [comment]
> 我现在想在assets加个音频文件，要怎么加？

1. 手动在flutter-assets中添加音频文件的资产声明

   ``` yaml
   ... 
   flutter:
     assets:
     # path/to/flutter_r_demo/assets/audios/test.mp3
     - assets/audios/test.mp3
     # path/to/flutter_r_demo/lib/assets/audios/test.mp3
     - packages/flutter_r_demo/assets/audios/test.mp3
   ...
   ```

2. 暂时使用 [flr-cli-3.1.0](https://rubygems.org/gems/flr) 或者 [flr-as-plugin-x.3.1.0](https://plugins.jetbrains.com/plugin/13789-flr/versions) 代替 flr-vscode-extension 作为你的 Flr 工具
3. 目前  [flr-cli-3.1.0](https://rubygems.org/gems/flr) 和 [flr-as-plugin-x.3.1.0](https://plugins.jetbrains.com/plugin/13789-flr/versions) 已经支持“自动合并旧的资产声明”——这意味着你手动添加的资产声明不会被Flr冲掉；但是 flr-vscode-extension-2.0.1（当前最新版本）尚未支持这特性，需要额外开发时间进行支持，敬请理解和期待
