### ISSUE TITLE
在Windows下使用资源的路径有问题

### ISSUE THREAD

**Issue by protosse** [Fly-Mix/flr-vscode-extension#2]
![image](https://user-images.githubusercontent.com/30048222/82917068-7cc61d00-9fa5-11ea-86b6-78343e5bd6a4.png)
mac下就是对的

**Comment by CodeEagle** [comment]
好的，pubspec.yaml 能贴一下么

**Comment by protosse** [comment]
```
name: noonelive
description: A new Flutter application.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  dio: ^3.0.9
  flustars: ^0.3.2
  carousel_slider: ^2.1.0
  pull_to_refresh: ^1.5.8
  provider: ^4.1.0
  flutter_easyloading: ^1.1.3
  fluro: ^1.6.3
  crypto: ^2.1.4
  rxdart: ^0.24.0
  badges: ^1.1.1
  geolocator: ^5.3.1
  cached_network_image: ^2.2.0+1
  webview_flutter: ^0.3.22+1
  r_dart_library:
    git:
      url: 'https://github.com/YK-Unit/r_dart_library.git'
      ref: 0.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.9.0
  json_serializable: ^3.3.0
flutter:
  uses-material-design: true
  assets:
  - packages/noonelive/assets/images/activity/event_icon_collect.png
  - packages/noonelive/assets/images/activity/event_icon_collected.png
  - packages/noonelive/assets/images/activity/event_icon_date.png
  - packages/noonelive/assets/images/activity/event_icon_details.png
  - packages/noonelive/assets/images/activity/event_icon_other.png
  - packages/noonelive/assets/images/activity/event_icon_share.png
  - packages/noonelive/assets/images/activity/event_icon_unit.png
flr:
  core_version: 3.0.0
  dartfmt_line_length: 80
  assets:
  - lib/assets/images
  fonts: []

```
这个是我在Mac下生成的，家里才有PC，区别就是windows下生成的文件路径都是带盘符的绝对路径，Mac下是相对路径
