### ISSUE TITLE
AssetSvg.load overriden method has fewer positional args

### ISSUE THREAD

**Issue by pouyaam** [Fly-Mix/flr-vscode-extension#3]
Hi

I get the following error 
Error: The method 'AssetSvg.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'

When I investiage, asset_svg.dart has been extended from ImageProvider<T> which has a load method that has 2 arguments

Thanks

**Comment by YK-Unit** [comment]
Please send us the following infos:

- flutter version
- flr-vscode-extension version

**Comment by pouyaam** [comment]
Flutter version: 1.17.2
flr-vscode-extension: 2.1.1

**Comment by CodeEagle** [comment]
@pouyaam It'll fixed at next version, is a bug in calculating r_dart_library version. Sorry for your inconvenience.

**Comment by YK-Unit** [comment]
@pouyaam to fix this bug manually, you can set the ref of r_dart_library as `0.2.1` :

```yaml
# your project's pubsepc.yaml

dependencies:
  r_dart_library:
    git:
      url: https://github.com/YK-Unit/r_dart_library.git
      ref: 0.2.1
```
